### ISSUE TITLE
KBQA rus performance

### ISSUE THREAD

**Issue by roman-vygon** [deepmipt/DeepPavlov#1477] opened 2021-08-22 11:30 UTC
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
deeppavlov 0.16.0

**Python version**:
3.8
**Operating system** (ubuntu linux, windows, ...):
Colab
**Issue**:
Russian Knowledge-based Question Answering pipeline is acting weird, it almost always outputs 'Not Found'. or irrelevant answer. Any date-like answer is in English instead of Russian. To the question 'Когда родился Пушкин?' it outputs 7th May 1766 which is his uncles' birthday I guess.

Is it because I'm using smaller wikipedia dump (20GB hdt file + 10GB index), or is something off with the models\configuration?

**Command that led to error**:
```
from deeppavlov import configs, build_model

kbqa_model = build_model(configs.kbqa.kbqa_cq_rus, download=True)
kbqa_model(['Когда родился Пушкин?'])

```

**Error (including full traceback)**:
```
Wrong answers :(
```

**Comment by dmitrijeuseew** [comment] 2021-08-22 11:53
We will find the cause of the bug and fix it in the next release of the library.

**Comment by dmitrijeuseew** [comment] 2022-06-24 11:04
The issue is fixed in https://github.com/deepmipt/DeepPavlov/pull/1516

**Closed** 2022-06-24 11:05 UTC
Labels: bug
